import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./components/footer";
import Headr from "./components/headr";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <Headr />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
